FROM oven/bun:1

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /usr/src/app

COPY package.json bun.lock turbo.json ./
COPY apps/backend/package.json apps/backend/package.json
COPY packages/db/package.json packages/db/package.json

RUN bun install

COPY . .

RUN test -n "$DATABASE_URL"
RUN bun run generate:db

EXPOSE 8080

CMD ["bun", "start:backend"]
