name: Continuous Deployment (Prod) (Backend)

on: 
  push: 
    branches: [main]
env:
  DOCKERHUB_NAMESPACE: ayush160
  IMAGE_NAME: user-app-backend

jobs: 
  build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: apps/backend/Dockerfile.backend
            push: true
            tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}